# Generated by Django 1.11.24 on 2021-07-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0008_auto_20190916_0235"),
    ]

    operations = [
        migrations.RemoveField(model_name="taskstoreactivity", name="store",),
        migrations.DeleteModel(name="TaskStoreActivity",),
    ]
