# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-10 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_auto_20190916_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstoreactivity',
            name='store',
        ),
        migrations.DeleteModel(
            name='TaskStoreActivity',
        ),
    ]
