# Generated by Django 1.11.29 on 2021-07-31 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0008_auto_20190916_0235"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskstoreactivity",
            name="store",
        ),
        migrations.AlterField(
            model_name="usermetadata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="TaskStoreActivity",
        ),
    ]
