# Generated by Django 1.11.29 on 2021-11-28 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0009_auto_20210731_2340"),
    ]

    operations = [
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.UUIDField()),
                ("field", models.CharField(max_length=255)),
                ("data_from", models.TextField()),
                ("data_to", models.TextField()),
                ("changed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-changed"],
            },
        ),
        migrations.CreateModel(
            name="ChangeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sourcetype",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Direct/API"),
                            (2, "Sync"),
                            (3, "Revert"),
                            (5, "Garbage Collection"),
                            (6, "Autoconfiguration"),
                            (20, "Incoming E-mail"),
                            (25, "Incoming SMS"),
                            (21, "Trello (Outgoing)"),
                            (22, "Trello (Incoming)"),
                            (23, "Trello (Reconciliation)"),
                            (23, "Trello (Reset)"),
                        ]
                    ),
                ),
                ("foreign_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("finished", models.DateTimeField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="taskmanager.TaskStore",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="change",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="taskmanager.ChangeSource",
            ),
        ),
    ]
