# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-10 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_auto_20210710_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to=settings.AUTH_USER_MODEL),
        ),
    ]
