# Generated by Django 1.11.29 on 2021-12-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0010_auto_20211128_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changesource",
            name="sourcetype",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Direct/API"),
                    (2, "Sync"),
                    (3, "Revert"),
                    (4, "Deduplication"),
                    (5, "Garbage Collection"),
                    (6, "Autoconfiguration"),
                    (20, "Incoming E-mail"),
                    (25, "Incoming SMS"),
                    (21, "Trello (Outgoing)"),
                    (22, "Trello (Incoming)"),
                    (23, "Trello (Reconciliation)"),
                    (23, "Trello (Reset)"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="trelloobjectaction",
            name="action_id",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
