# Generated by Django 1.11.29 on 2021-12-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0011_auto_20211220_1651"),
    ]

    operations = [
        migrations.AddField(
            model_name="changesource",
            name="commit_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
