# Generated by Django 1.11.29 on 2022-01-23 00:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0012_changesource_commit_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="TaskData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "predecessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successors",
                        to="taskmanager.TaskData",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="changesource",
            name="sourcetype",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Direct/API"),
                    (2, "Sync"),
                    (3, "Revert"),
                    (4, "Deduplication"),
                    (5, "Garbage Collection"),
                    (6, "Autoconfiguration"),
                    (7, "Backfill"),
                    (20, "Incoming E-mail"),
                    (25, "Incoming SMS"),
                    (21, "Trello (Outgoing)"),
                    (22, "Trello (Incoming)"),
                    (23, "Trello (Reconciliation)"),
                    (23, "Trello (Reset)"),
                ]
            ),
        ),
        migrations.AddField(
            model_name="taskdata",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_datas",
                to="taskmanager.ChangeSource",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="latest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taskmanager.TaskData"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="taskmanager.TaskStore",
            ),
        ),
    ]
