# Generated by Django 1.11.29 on 2021-12-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0012_changesource_commit_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changesource",
            name="commit_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="changesource",
            name="foreign_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
