# Generated by Django 1.11.29 on 2021-12-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0013_auto_20211221_0356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="changed",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="change",
            name="task_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="changesource",
            name="created",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="changesource",
            name="finished",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
