# Generated by Django 1.11.29 on 2022-01-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0013_auto_20220123_0054"),
        ("taskmanager", "0014_auto_20211221_0409"),
    ]

    operations = []
